### ISSUE TITLE
Example App Stuck on Biometric Consent Page

### ISSUE THREAD

**Issue by muruthi** [Mastercard/community-pass-flutter-wrapper#3]
- [ ] Contribution instructions do not contain content on how to run the Example App
- [x] Biometric Consent page does not call the wrapper implementation

> ```
> E/flutter (20765): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No 
> implementation found for method saveBiometricConsent on channel flutter_cpk_plugin)
> E/flutter (20765): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:313:7)
> E/flutter (20765): <asynchronous suspension>
> E/flutter (20765): #1      _BiometricConsentScreenState.saveBiometricConsent (package:flutter_cpk_plugin_example/biometricConsentScreen.dart:33:16)
> E/flutter (20765): <asynchronous suspension>
> E/flutter (20765): 
> ```

**Comment by Harry3167** [comment]
Resolved.
